# --- Moteur graphique ---
vo=gpu-next
gpu-api=vulkan
# Utilisation de x11vk (XWayland) car 'ontop' est incompatible avec Wayland natif
# voir : https://github.com/mpv-player/mpv/issues/3832
gpu-context=x11vk

# --- Accélération matérielle NVIDIA ---
hwdec=nvdec

# --- Optimisation pour ton LG OLED 42C2 ---
target-colorspace-hint=yes
fullscreen=no

# --- Qualité d'image maximale ---
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

# Fenêtre plus grande par défaut
autofit=50%          # 50% de l'écran
autofit-larger=80%   # jamais plus grand que 80%

# Reprendre la lecture au même endroit
save-position-on-quit=yes
volume=30


